version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3

    steps:
        - checkout
        - run: npm install
        - run: npm test
        - run: 
            name: Deploy Master to Heroku
            command: git push https://heroku:process.env.HEROKU_API_KEY@git.heroku.com/colabor8-us.git master

    